# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: News
    link: /news
  - submenu:
        - label: Compositions
          link: /compositions
        - label: Installations
          link: /installations
  - submenu:
        - label: Biography
          link: /pages/biography
        - label: Press
          link: /pages/press
  - label: Contact
    link: /pages/contact
