# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: News
    link: /seiten/news
  - submenu:
        - label: Compositions
          link: compositions
        - label: Installations
          link: Installations
  - submenu:
        - label: Biography
          link: biography
        - label: Press
          link: press
  - label: Contact
    link: contact
